# Generated by Django 3.2.15 on 2022-10-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_alter_webpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
