# Generated by Django 3.2.15 on 2022-10-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_alter_webpage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=200)),
                ('ecity', models.CharField(max_length=200)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
