# Generated by Django 3.2.15 on 2022-10-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
